language: rust
cache: cargo
before_script:
  - sudo apt update
  - sudo apt -y install libgtk-3-dev
  - rustup component add clippy
script:
  - cargo build
  - cargo clippy -- -D warnings
  - cargo test
  